export const images = [
  {
    img: "images/img1.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img2.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img3.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img4.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img5.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img6.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img7.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img8.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img9.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img10.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img11.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img12.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img13.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img14.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img15.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img16.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img17.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img18.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img19.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img20.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img21.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img22.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img23.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img24.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img25.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img26.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (27).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img28.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img29.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img30.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img31.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img32.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img33.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img34.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img35.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img36.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img37.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img38.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img39.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img40.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img41.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img42.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img43.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img44.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img45.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img46.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img47.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img48.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img49.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img50.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img51.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img52.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img53.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img54.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img55.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img56.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img57.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img58.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img59.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img60.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img61.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img62.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img63.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img64.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img65.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img66.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img67.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img68.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img69.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img70.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img71.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img72.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img73.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img74.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img75.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img76.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img77.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img78.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img79.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img80.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img81.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img82.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img83.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img84.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img85.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img86.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img87.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img88.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img89.jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img90.jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
];