export const images = [
  {
    img: "images/img (1).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (2).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (3).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (4).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (5).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (6).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (7).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (8).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (9).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (10).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (11).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (12).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (13).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (14).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (15).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (16).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (17).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (18).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (19).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (20).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (21).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (22).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (23).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (24).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (25).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (26).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (27).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (28).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (29).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (30).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (31).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (32).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (33).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (34).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (35).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (36).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (37).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (38).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (39).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (40).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (41).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (42).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (43).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (44).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (45).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (46).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (47).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (48).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (49).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (50).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (51).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (52).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (53).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (54).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (55).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (56).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (57).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (58).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (59).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (60).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (61).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (62).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (63).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (64).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (65).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (66).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (67).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (68).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (69).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (70).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (71).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (72).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (73).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (74).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (75).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (76).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (77).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (78).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (79).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (80).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    id: "2",
    img: "images/img (81).jpg",
    height: 250,
    alt: "concert photo people dancing",
  },
  {
    img: "images/img (82).jpg",
    height: 400,
    alt: "concert photo people dancing",
  },
  // {
  //   img: "images/img (83).jpg",
  //   height: 400,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   id: "2",
  //   img: "images/img (84).jpg",
  //   height: 250,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   img: "images/img (85).jpg",
  //   height: 400,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   id: "2",
  //   img: "images/img (86).jpg",
  //   height: 250,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   img: "images/img (87).jpg",
  //   height: 400,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   id: "2",
  //   img: "images/img (88).jpg",
  //   height: 250,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   img: "images/img (89).jpg",
  //   height: 400,
  //   alt: "concert photo people dancing",
  // },
  // {
  //   id: "2",
  //   img: "images/img (90).jpg",
  //   height: 250,
  //   alt: "concert photo people dancing",
  // },
];